// Gaussian random numbers. Write a program RandomGaussian
// that prints a random number r drawn from the Gaussian distribution. One way to
// do so is to use the Box–Muller formula
// r = sin(2  v) (2 ln u)1/2
// where u and v are real numbers between 0 and 1 generated by the Math.random()
// method.

public class GaussianRandomNumber {
    public static void main(String[] args) {
        // Generate two random values between 0 and 1
        double u = Math.random();
        double v = Math.random();

        // Apply the Box-Muller formula to calculate the Gaussian random number
        double r = Math.sin(2 * Math.PI * v) * Math.sqrt(-2 * Math.log(u));

        // Print the generated Gaussian random number
        System.out.println("Gaussian Random Number: " + r);
    }
}
